name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/release.yml'

jobs:
  test:
    strategy:
      matrix:
        python: ['3.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install flake8
    - name: Lint
      run: python -m flake8 src --exit-zero --max-line-length=88 --extend-ignore=E402 --max-complexity=10
    - name: Lint Tests
      run: python -m flake8 tests --exit-zero --max-line-length=88 --extend-ignore=E402 --max-complexity=10

